spring:
  application:
    name: service-registry

  cloud:
    config:
      import: "configserver:"
      uri: http://<VM_IP>:9000   # <-- GCP VM IP or localhost if local testing

server:
  port: 9001