spring:
  application:
    name: service-registry

  config:
    import: "optional:configserver:http://localhost:9000"  # optional make it safe

server:
  port: 9001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false