spring:
  application:
    name: service-registry

  config:
    import: "configserver:"


  cloud:
    config:
      uri: http://config.platform:9000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false